eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
    instance:
        hostname: localhost
server:
    port: 8761
spring:
    application:
        name: service-registry
