services:
  postgresql-financeiro:
    extends:
      file: financeiro/src/main/docker/postgresql.yml
      service: financeiro-db

  postgresql-seguranca:
    extends:
      file: seguranca/src/main/docker/postgresql.yml
      service: seguranca-db

  rabbitMQ:
    extends:
      file: docker/rabbitmq.yml
      service: rabbitmq

  elasticsearch:
    extends:
      file: docker/elasticStack/elastic-stack.yml
      service: elasticsearch

  kibana:
    extends:
      file: docker/elasticStack/elastic-stack.yml
      service: kibana

  logstash:
    extends:
      file: docker/elasticStack/elastic-stack.yml
      service: logstash

networks:
  elastic:
    driver: bridge