version: '3.8'
services:
  postgresql-financeiro:
    extends:
      file: financeiro/src/main/docker/postgresql.yml
      service: financeiro-db
    container_name: financeiro-db
  postgresql-seguranca:
    extends:
      file: seguranca/src/main/docker/postgresql.yml
      service: seguranca-db
    container_name: seguranca-db
  rabbitMQ:
    extends:
      file: docker/rabbitmq.yml
      service: rabbitmq
    container_name: rabbitmq