version: '3.8'
services:
  postgresql-financeiro:
    extends:
      file: financeiro/src/main/docker/postgresql.yml
      service: financeiro-db
    container_name: financeiro-db
  seguranca-db:
    extends:
      file: seguranca/src/main/docker/postgresql.yml
      service: seguranca-db
    container_name: seguranca-db