apiVersion: apps/v1
kind: Deployment
metadata:
  name: financeiro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: financeiro
  template:
    metadata:
      labels:
        app: financeiro
    spec:
      containers:
      - name: financeiro
        image: rodr1gocosta/controlefinanceiro-financeiro:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - name: http
          containerPort: 8082
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: PORT
          value: "8082"
        - name: JDBC_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: financeiro-secret
              key: DATABASE_URL
        - name: JDBC_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: financeiro-secret
              key: POSTGRES_USER
        - name: JDBC_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: financeiro-secret
              key: POSTGRES_PASSWORD
        - name: CLOUDAMQP_URL
          valueFrom:
            secretKeyRef:
              name: broker-secret
              key: CLOUDAMQP_URL
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SECRET
        - name: EUREKA_USERNAME
          valueFrom:
            secretKeyRef:
              name: eureka-registry-secret
              key: EUREKA_USERNAME
        - name: EUREKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eureka-registry-secret
              key: EUREKA_PASSWORD
        - name: EUREKA_HOSTNAME
          value: financeiro
        - name: EUREKA_URI
          value: http://${authConfig.serviceRegistry.username}:${authConfig.serviceRegistry.password}@serviceregistry:8761/eureka/
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 3
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 3
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: financeiro
spec:
  type: ClusterIP
  selector:
    app: financeiro
  ports:
  - name: http
    port: 8082
    targetPort: 8082
    protocol: TCP

