apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: rodr1gocosta/controlefinanceiro-gateway:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: PORT
          value: "8080"
        - name: SECRET
          value: "123secret"
        - name: EUREKA_USERNAME
          value: service-registry-prod
        - name: EUREKA_PASSWORD
          value: "1020304050s"
        - name: EUREKA_HOSTNAME
          value: gateway
        - name: EUREKA_URI
          value: http://${authConfig.serviceRegistry.username}:${authConfig.serviceRegistry.password}@serviceregistry:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 31000
