apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificacao
  namespace: homologacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificacao
  template:
    metadata:
      labels:
        app: notificacao
    spec:
      containers:
      - name: notificacao
        image: rodr1gocosta/controlefinanceiro-notificacao:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - name: http
          containerPort: 8083
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: PORT
          value: "8083"
        - name: EMAIL_HOST
          value: smtp.gmail.com
        - name: EMAIL_PORT
          value: "587"
        - name: EMAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: notificacao-secret
              key: EMAIL_USERNAME
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notificacao-secret
              key: EMAIL_PASSWORD
        - name: CLOUDAMQP_URL
          valueFrom:
            secretKeyRef:
              name: broker-secret
              key: CLOUDAMQP_URL
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SECRET
        - name: EUREKA_USERNAME
          valueFrom:
            secretKeyRef:
              name: eureka-registry-secret
              key: EUREKA_USERNAME
        - name: EUREKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eureka-registry-secret
              key: EUREKA_PASSWORD
        - name: EUREKA_HOSTNAME
          value: notificacao
        - name: EUREKA_URI
          value: http://${authConfig.serviceRegistry.username}:${authConfig.serviceRegistry.password}@serviceregistry:8761/eureka/
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 3
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 3
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: notificacao
  namespace: homologacao
spec:
  type: ClusterIP
  selector:
    app: notificacao
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    protocol: TCP
