apiVersion: apps/v1
kind: Deployment
metadata:
  name: seguranca
  namespace: homologacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seguranca
  template:
    metadata:
      labels:
        app: seguranca
    spec:
      containers:
      - name: seguranca
        image: rodr1gocosta/controlefinanceiro-seguranca:latest
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        ports:
          - name: http
            containerPort: 8081
            protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: PORT
          value: "8081"
        - name: JDBC_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: seguranca-secret
              key: DATABASE_URL
        - name: JDBC_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: seguranca-secret
              key: POSTGRES_USER
        - name: JDBC_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: seguranca-secret
              key: POSTGRES_PASSWORD
        - name: CLOUDAMQP_URL
          valueFrom:
            secretKeyRef:
              name: broker-secret
              key: CLOUDAMQP_URL
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SECRET
        - name: EUREKA_USERNAME
          valueFrom:
            secretKeyRef:
              name: eureka-registry-secret
              key: EUREKA_USERNAME
        - name: EUREKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eureka-registry-secret
              key: EUREKA_PASSWORD
        - name: EUREKA_HOSTNAME
          value: seguranca
        - name: EUREKA_URI
          value: http://${authConfig.serviceRegistry.username}:${authConfig.serviceRegistry.password}@serviceregistry:8761/eureka/
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 3
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 3
          timeoutSeconds: 10
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: seguranca
  namespace: homologacao
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: seguranca
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: seguranca
  namespace: homologacao
spec:
  type: ClusterIP
  selector:
    app: seguranca
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
