server:
  port: 8082

spring:
  application:
    name: financeiro

  datasource:
    url: jdbc:postgresql://localhost:5433/financeiro-db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    addresses: amqps://zqlkokyg:LjRJD3AV8OwPdDVAK8o7QGNSJDCjoG5b@chimpanzee.rmq.cloudamqp.com/zqlkokyg

broker:
  queue:
    financeiro:
      name: default.user

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka
