spring:
    application:
        name: seguranca
    profiles:
        active: dev
    config:
        import: 'configserver:'
    cloud:
        config:
            discovery:
                service-id: config-server