server:
    port: 8081
spring:
    application:
        name: seguranca
    datasource:
        url: jdbc:postgresql://localhost:5432/seguranca-db
        username: postgres
        password: root
    jpa:
        hibernate:
            ddl-auto: none
    liquibase:
        change-log: liquibase/master.xml

api:
    securty:
        token:
            secret: 123456
eureka:
    client:
        serviceUrl:
            defaultzone: http://localhost:8761/eureka


