spring:
    application:
        name: seguranca
    profiles:
        active: dev
    config:
        import: 'configserver:'
    cloud:
        config:
            discovery:
                service-id: config-server


#    datasource:
#        url: jdbc:postgresql://localhost:5432/seguranca-db
#        username: postgres
#        password: root
#    jpa:
#        hibernate:
#            ddl-auto: none
#    liquibase:
#        change-log: liquibase/master.xml
#    rabbitmq:
#        host: localhost
#        port: 5672
#        username: admin
#        password: admin
#    cloud:
#      stream:
#          bindings:
#              userEventSupplier-out-0:
#                  destination: seguranca.event.newUser
#              userNewPasswordEventSupplier-out-0:
#                  destination: seguranca.event.newUserPassword
#
#api:
#    securty:
#        token:
#            secret: 123456
#
#eureka:
#    client:
#        serviceUrl:
#            defaultzone: http://localhost:8761/eureka


