services:
  financeiro-db:
    image: postgres:14
    container_name: financeiro-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB_FINANCEIRO}
      POSTGRES_USER: ${POSTGRES_USER_FINANCEIRO}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_FINANCEIRO}
    ports:
      - "5433:5432"
    volumes:
      - ~/.volume/postgresql/financeiro:/var/lib/postgresql/data