spring:
    application:
        name: gateway
    profiles:
        active: dev
    config:
        import: 'configserver:'
    cloud:
        config:
            discovery:
                service-id: config-server

#    cloud:
#        gateway:
#            routes:
#            - id: seguranca
#              uri: lb://seguranca
#              predicates:
#                  - Path=/api/security/**
#              filters:
#                - TokenValidationFilter
#
#
#            - id: financeiro
#              uri: lb://financeiro
#              predicates:
#                - Path=/api/financas/**
#              filters:
#                - TokenValidationFilter
#
#eureka:
#    client:
#        serviceUrl:
#            defaultzone: http://localhost:8761/eureka
#
#api:
#    securty:
#        token:
#            secret: 123456