server:
    port: 8080

spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes:
            - id: seguranca
              uri: lb://seguranca
              predicates:
                  - Path=/api/security/**
              filters:
                - TokenValidationFilter

eureka:
    client:
        serviceUrl:
            defaultzone: http://localhost:8761/eureka

api:
    securty:
        token:
            secret: 123456