server:
    port: ${PORT}
spring:
    cloud:
        gateway:
            routes:
                - id: seguranca
                  uri: lb://seguranca
                  predicates:
                    - Path=/api/security/**
                  filters:
                    - TokenValidationFilter

                - id: financeiro
                  uri: lb://financeiro
                  predicates:
                    - Path=/api/financas/**
                  filters:
                    - TokenValidationFilter

api:
    securty:
        token:
            secret: ${SECRET}

authConfig:
    serviceRegistry:
        username: ${EUREKA_USERNAME}
        password: ${EUREKA_PASSWORD}


eureka:
    instance:
        hostname: ${EUREKA_HOSTNAME}
    client:
        serviceUrl:
            defaultZone: http://${authConfig.serviceRegistry.username}:${authConfig.serviceRegistry.password}@${eureka.instance.hostname}:8761/eureka/