version: '3.8'
services:
  service-registry:
    image: docker.io/rodr1gocosta/controlefinanceiro-service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
      
  config-server:
    image: docker.io/rodr1gocosta/controlefinanceiro-configserver
    container_name: config-server
    ports:
      - "8888:8888"