spring:
    application:
        name: notificacao
    profiles:
        active: dev
    config:
        import: 'configserver:'
    cloud:
        config:
            discovery:
                service-id: config-server
            username: configserver
            password: '12345678c'
