server:
  port: 8083

spring:
  application:
    name: notificacao
  mail:
    host: smtp.gmail.com
    port: 587
    username: if.inteligenciafinanceira2023@gmail.com
    password: msnf trfw vebz jiah
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka

