server:
    port: 8083
spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: if.inteligenciafinanceira2023@gmail.com
        password: msnf trfw vebz jiah
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    rabbitmq:
        host: localhost
        port: 5672
        username: admin
        password: admin
    cloud:
        stream:
            bindings:
                userNewPasswordConsumer-in-0:
                    destination: seguranca.event.newUserPassword
                    group: notificacao
            rabbit:
                bindings:
                    userNewPasswordConsumer-in-0:
                        consumer:
                            auto-bind-dlq: true
        function:
          definition: userNewPasswordConsumer;

authConfig:
    serviceRegistry:
        username: serviceregistry
        password: '12345678'

api:
    security:
        token:
            secret: 123456

eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://${authConfig.serviceRegistry.username}:${authConfig.serviceRegistry.password}@${eureka.instance.hostname}:8761/eureka/