spring:
    application:
        name: notificacao
    profiles:
        active: dev

management:
    endpoints:
        web:
            exposure:
                include: health
    endpoint:
        health:
            show-details: always
