server:
  port: 8888
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rodr1gocosta/Controle-Financeiro-Inteligente_config-server
          default-label: main

eureka:
  client:
    serviceUrl:
      defaultzone: http://localhost:8761/eureka