server:
  port: ${PORT}
spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_URI}
          default-label: main

authConfig:
  configServer:
    username: ${CONFIG_USERNAME}
    password: ${CONFIG_PASSWORD}
  serviceRegistry:
    username: ${EUREKA_USERNAME}
    password: ${EUREKA_PASSWORD}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
