version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: db-user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db-user
    ports:
      - "5432:5432"
    volumes:
      - ~/.volume/postgresql:/var/lib/postgresql/data