services:
  seguranca-db:
    image: postgres:14
    container_name: seguranca-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB_SEGURANCA}
      POSTGRES_USER: ${POSTGRES_USER_SEGURANCA}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_SEGURANCA}
    ports:
      - "5432:5432"
    volumes:
      - ~/.volume/postgresql/seguranca:/var/lib/postgresql/data