version: '3'
services:
  seguranca-db:
    image: postgres:14
    container_name: seguranca-db
    environment:
      POSTGRES_DB: seguranca-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ~/.volume/postgresql/seguranca:/var/lib/postgresql/data