name: CI/CD

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build JAR for service-registry
      run: mvn clean package -pl service-registry -am

    - name: Build and push Docker images
    - uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: service-registry/Dockerfile
        push: true
        tags: rodr1gocosta/controlefinanceiro-service-registry:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
