name: CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build JAR for service-registry
      run: mvn clean package -pl service-registry -am
      
    - name: List contents of target directory
      run: ls -l service-registry/target

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        Username: ${{ secrets.DOCKERHUB_USERNAME }}
        Password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: service-registry/Dockerfile
        push: true
        tags: | 
          rodr1gocosta/controlefinanceiro-service-registry:v${{github.run_number}}
          rodr1gocosta/controlefinanceiro-service-registry:latest

