name: CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pegar o código no repositório
      uses: actions/checkout@v3
    
    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Buildar JAR para service-registry
      run: mvn clean package -pl service-registry -am

    - name: Buildar JAR para config-server
      run: mvn clean package -pl config-server -am

    # Build sem os testes temporario
    - name: Buildar JAR para gateway
      run: mvn clean package -pl gateway -am -DskipTests

    - name: Buildar JAR para seguranca
      run: mvn clean package -pl seguranca -am -DskipTests

    - name: Buildar JAR para financeiro
      run: mvn clean package -pl financeiro -am -DskipTests

    - name: Buildar JAR para notificacao
      run: mvn clean package -pl notificacao -am -DskipTests

    - name: Uploadar JARs como artefatos
      uses: actions/upload-artifact@v3
      with:
        name: built-jars
        path: |
          service-registry/target/*.jar
          config-server/target/*.jar
          gateway/target/*.jar
          seguranca/target/*.jar
          financeiro/target/*.jar
          notificacao/target/*.jar

  docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Pegar o código no repositório
      uses: actions/checkout@v3

    - name: Baixar JARs construídos
      uses: actions/download-artifact@v3
      with:
        name: built-jars
        path: .

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        Username: ${{ secrets.DOCKERHUB_USERNAME }}
        Password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Buildar e enviar para Docker a image service-registry
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: service-registry/Dockerfile
        push: true
        tags: | 
          rodr1gocosta/controlefinanceiro-service-registry:v${{github.run_number}}
          rodr1gocosta/controlefinanceiro-service-registry:latest

    - name: Buildar e enviar para Docker a image config-server
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: config-server/Dockerfile
        push: true
        tags: | 
            rodr1gocosta/controlefinanceiro-config-server:v${{github.run_number}}
            rodr1gocosta/controlefinanceiro-config-server:latest

    - name: Buildar e enviar para Docker a image gateway
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: gateway/Dockerfile
        push: true
        tags: | 
            rodr1gocosta/controlefinanceiro-gateway:v${{github.run_number}}
            rodr1gocosta/controlefinanceiro-gateway:latest