name: CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pegar o código no repositório
      uses: actions/checkout@v3
    
    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build JAR for service-registry
      run: mvn clean package -pl service-registry -am

    - name: Build JAR for config-server
      run: mvn clean package -pl config-server -am

    - name: Build JAR for gateway
      run: mvn clean package -pl gateway -am

    - name: Build JAR for seguranca
      run: mvn clean package -pl seguranca -am

    - name: Build JAR for notificacao
      run: mvn clean package -pl notificacao -am
      
    # - name: List contents of target directory
    #   run: ls -l service-registry/target

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        Username: ${{ secrets.DOCKERHUB_USERNAME }}
        Password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: service-registry/Dockerfile
        push: true
        tags: | 
          rodr1gocosta/controlefinanceiro-service-registry:v${{github.run_number}}
          rodr1gocosta/controlefinanceiro-service-registry:latest

    - name: Build and push Docker image for config-server
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: config-server/Dockerfile
        push: true
        tags: | 
            rodr1gocosta/controlefinanceiro-config-server:v${{github.run_number}}
            rodr1gocosta/controlefinanceiro-config-server:latest
